name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create User if Not Exists
        run: |
          psql -h localhost -U postgres -p 5432 -c 
          "CREATE USER IF NOT EXISTS ${{ secrets.PGUSER_TEST }} 
          WITH PASSWORD '${{ secrets.PGPASSWORD_TEST }}';"

      - name: Create Database if Not Exists
        run: |
          psql -h localhost -U postgres -p 5432 -c 
          "CREATE DATABASE IF NOT EXISTS ${{ secrets.PGDATABASE_TEST }};"

      - name: npm install, migrate and test
        run: |
          npm install
          npm run migrate:up test
          npm run test
        env:
          CI: true
          PGHOST: ${{ secrets.PGHOST_TEST }}
          PGUSER: ${{ secrets.PGUSER_TEST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }}
          PGDATABASE: ${{ secrets.PGDATABASE_TEST }}
          PGPORT: ${{ secrets.PGPORT_TEST }}
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
